// examples/svelte/src/TourCard.svelte
<script lang="ts">
import type { RenderContext } from '@docentjs/core'

let { ctx }: { ctx: RenderContext } = $props()
let liked = $state(false)
</script>

<div class="tour-card">
  <h3>{ctx.step.title}</h3>
  {#if ctx.step.body}<p>{ctx.step.body}</p>{/if}
  <footer>
    <span class="dots">
      {#each { length: ctx.progress.total } as _, i (i)}
        <i class:on={i + 1 === ctx.progress.current}></i>
      {/each}
    </span>
    <button type="button" aria-pressed={liked} onclick={() => (liked = !liked)}>{liked ? '♥' : '♡'}</button>
    {#if ctx.canGoBack}<button type="button" onclick={ctx.actions.back}>Back</button>{/if}
    <button type="button" class="primary" onclick={ctx.actions.next}>{ctx.isLast ? 'Done' : 'Next'}</button>
  </footer>
</div>

// examples/react/src/TourCard.tsx
import type { RenderContext } from '@docentjs/core'
import { useState } from 'react'

/** A fully custom popover. Receives the render context, owns its own state. */
export function TourCard({ ctx }: { ctx: RenderContext }) {
  const [liked, setLiked] = useState(false)
  const { step, progress, actions, isLast, canGoBack } = ctx
  return (
    <div className="tour-card">
      <h3>{step.title}</h3>
      {step.body && <p>{step.body}</p>}
      <footer>
        <span className="dots">
          {Array.from({ length: progress.total }, (_, i) => (
            <i key={String(i)} className={i + 1 === progress.current ? 'on' : ''} />
          ))}
        </span>
        <button type="button" onClick={() => setLiked((v) => !v)} aria-pressed={liked}>
          {liked ? '♥' : '♡'}
        </button>
        {canGoBack && (
          <button type="button" onClick={actions.back}>
            Back
          </button>
        )}
        <button type="button" className="primary" onClick={actions.next}>
          {isLast ? 'Done' : 'Next'}
        </button>
      </footer>
    </div>
  )
}
